name: Ansible

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Git Clone/Pull
      - uses: actions/checkout@v3

      - name: Check Ansible Version
        run: ansible --version 

      - name: Generate Key
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key
          chmod 400 ansible_key

      - name: Check Inventory
        run: ansible-inventory -i aws_ec2.yml --list



      

