name: Ansible

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Git Clone/Pull
      - uses: actions/checkout@v3

      - name: Check Ansible Version
        run: ansible --version 

